# Generated by Django 5.2.1 on 2025-05-29 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=100)),
                ('reporting_period', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_units', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('environmental', 'Environmental'), ('social', 'Social'), ('governance', 'Governance')], max_length=20)),
                ('value', models.FloatField()),
                ('year', models.PositiveIntegerField()),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.businessunit')),
            ],
        ),
    ]
